name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Create temp Flutter project
        run: flutter create temp_app

      - name: Copy your code into project
        run: |
          rm -rf temp_app/lib
          cp -r lib temp_app/

          cp pubspec.yaml temp_app/pubspec.yaml

      - name: Install dependencies
        run: |
          cd temp_app
          flutter pub get

      - name: Build RELEASE APK
        run: |
          cd temp_app
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: study-with-ts-apk
          path: temp_app/build/app/outputs/flutter-apk/app-release.apk
